import type { ModernArchivistEpisode } from "./types";

export const modernArchivistFixture: ModernArchivistEpisode = {
  episode_id: "modern-archivist-retention-demo",
  title: "The Backup That Never Existed",
  duration_seconds: 42,
  sections: [
    { id: "s01_hook", start: 0, end: 6, text: "The company said every customer file was backed up. The logs said otherwise.", tags: [{ at: 0, type: "layout", value: "STATE_MONOLOGUE" }], narrative_phase: "hook", retention_device: "cold_open_shock", visual_mode: "monologue", layout: "anchor_center", color_state: "teal", evidence_refs: ["claim_001", "source_001"], evidence_role: "derived_analysis", estimated_duration_seconds: 6 },
    { id: "s02_case_file", start: 6, end: 13, text: "First, the pitch deck promised redundant backups. Then the incident report quietly removed the word redundant.", tags: [], narrative_phase: "context", retention_device: "contradiction_reveal", visual_mode: "case_file", layout: "evidence_board", color_state: "teal", evidence_refs: ["source_001", "source_002"], evidence_role: "primary_evidence", estimated_duration_seconds: 7, media_overlay: { id: "case-001", kind: "case_file_sequence", title: "The backup claim", evidence_role: "primary_evidence", evidence_refs: ["source_001", "source_002"], stamp: "CONTRADICTION", beats: [{ label: "CLAIM", claim: "Redundant daily backups" }, { label: "RECEIPT", claim: "Only one storage region configured" }, { label: "CONTRADICTION", claim: "Incident report deletes redundancy language" }], motion_plan: [{ at_seconds: 0, action: "show_claim_card" }, { at_seconds: 2, action: "reveal_contradiction" }] } },
    { id: "s03_failure_graph", start: 13, end: 20, text: "The failure path was not one bug. It was sales pressure, missing monitoring, and a restore process nobody tested.", tags: [], narrative_phase: "deep_dive", retention_device: "mechanism_explanation", visual_mode: "failure_graph", layout: "data_chart", color_state: "teal", evidence_refs: ["claim_003"], evidence_role: "derived_analysis", estimated_duration_seconds: 7, media_overlay: { id: "graph-001", kind: "failure_graph", title: "How the backup failed", evidence_role: "derived_analysis", evidence_refs: ["claim_003"], nodes: [{ label: "Sales claim" }, { label: "One region" }, { label: "No restore drill" }, { label: "Customer loss" }], links: [{ from: 0, to: 1 }, { from: 1, to: 2 }, { from: 2, to: 3 }] } },
    { id: "s04_code", start: 20, end: 27, text: "The config was not ambiguous. Backup replication was disabled in the one file that mattered.", tags: [], narrative_phase: "deep_dive", retention_device: "evidence_receipt", visual_mode: "code_walkthrough", layout: "code_walkthrough", color_state: "teal", evidence_refs: ["repo_001"], evidence_role: "primary_evidence", estimated_duration_seconds: 7, media_overlay: { id: "code-001", kind: "code_walkthrough", title: "Backup config", filename: "backup.yaml", language: "yaml", content: "backup:\n  enabled: true\n  replication: false\n  restore_test: never", evidence_role: "primary_evidence", evidence_refs: ["repo_001"], highlights: [{ line: 3, label: "the quiet part" }] } },
    { id: "s05_interrupt", start: 27, end: 34, text: "That is not a backup strategy. That is a screenshot of a parachute.", tags: [], narrative_phase: "pattern_interrupt", retention_device: "comic_release", visual_mode: "critical_error", layout: "anchor_center", color_state: "red", evidence_refs: ["repo_001"], evidence_role: "derived_analysis", estimated_duration_seconds: 7, media_overlay: { id: "type-001", kind: "kinetic_typography", text: "SCREENSHOT OF A PARACHUTE", variant: "glitch_slam", evidence_role: "derived_analysis", evidence_refs: ["repo_001"] } },
    { id: "s06_metaphor", start: 34, end: 39, text: "When the outage arrived, the safety net was just theatre.", tags: [], narrative_phase: "why_it_matters", retention_device: "stakes_escalation", visual_mode: "cinematic_metaphor", layout: "media_full", color_state: "teal", evidence_refs: [], evidence_role: "illustrative_only", estimated_duration_seconds: 5, media_overlay: { id: "metaphor-001", kind: "cinematic_metaphor", title: "The server room goes dark", evidence_role: "illustrative_only", description: "Illustrative blackout visual", mood: "blackout", label: "ILLUSTRATIVE", motion_plan: [] } },
    { id: "s07_outro", start: 39, end: 42, text: "The ledger entry is simple: a promise is not infrastructure.", tags: [], narrative_phase: "outro", retention_device: "payoff", visual_mode: "outro", layout: "anchor_center", color_state: "teal", evidence_refs: ["claim_004"], evidence_role: "derived_analysis", estimated_duration_seconds: 3 },
  ],
  amplitude: Array.from({ length: 85 }, (_, index) => { const time = index * 0.5; const speakingWindows = (time > 0.5 && time < 5.6) || (time > 6.2 && time < 33.5) || (time > 34.2 && time < 41.5); return { time, volume: speakingWindows ? 0.18 + 0.07 * Math.sin(time * 7) : 0.01 }; }),
};

export const nikolaContentFixture: ModernArchivistEpisode = {
  episode_id: "nikola-content-fixture",
  title: "Nikola: Gravity Did the Driving",
  duration_seconds: 8,
  debug_disable_backdrop: true,
  sections: [
    {
      id: "nikola_source_montage",
      start: 0,
      end: 4,
      text: "The demo sold motion before the machine could prove it.",
      tags: [],
      narrative_phase: "hook",
      retention_device: "cold_open_shock",
      visual_mode: "source_montage",
      layout: "media_full",
      color_state: "teal",
      evidence_refs: ["source_001"],
      content_opportunity_refs: ["opp_001"],
      evidence_role: "primary_evidence",
      estimated_duration_seconds: 4,
      media_overlay: {
        id: "nikola-source-001",
        kind: "source_montage",
        title: "The rolling demo",
        evidence_role: "primary_evidence",
        evidence_refs: ["source_001"],
        content_opportunity_refs: ["opp_001"],
        rights_status: "needs_review",
        runtime_affinity: "remotion",
        sources: [
          { source: "Demo video", title: "Truck appears to drive" },
          { source: "Court record", title: "Hill roll allegation" },
          { source: "Investor deck", title: "Operational promise" },
        ],
      },
    },
    {
      id: "nikola_recreated_ui",
      start: 4,
      end: 8,
      text: "Then the claim gets rebuilt as an artifact the audience can inspect.",
      tags: [],
      narrative_phase: "context",
      retention_device: "contradiction_reveal",
      visual_mode: "recreated_ui",
      layout: "media_full",
      color_state: "teal",
      evidence_refs: ["source_002"],
      content_opportunity_refs: ["opp_002"],
      evidence_role: "primary_evidence",
      estimated_duration_seconds: 4,
      media_overlay: {
        id: "nikola-ui-001",
        kind: "recreated_ui",
        title: "Archived product claim",
        url: "archive.example/nikola-one",
        claim_highlight: "Zero-emissions semi truck shown in motion",
        evidence_role: "primary_evidence",
        evidence_refs: ["source_002"],
        content_opportunity_refs: ["opp_002"],
        rights_status: "recreate_only",
        runtime_affinity: "either",
        before_after: [
          { label: "Public claim" },
          { label: "Technical reality" },
          { label: "Legal finding" },
        ],
      },
    },
  ],
  amplitude: Array.from({ length: 17 }, (_, index) => ({ time: index * 0.5, volume: 0.14 })),
};
